"""add_preferred_gemini_model_to_user

Revision ID: 8ca98d3fe097
Revises: b1c2d3e4f5a6
Create Date: 2025-05-15 13:58:45.948089

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ca98d3fe097'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_gemini_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_gemini_model')
    # ### end Alembic commands ###
